name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build Sponge with Maven
      run: mvn -B package --file ${{ github.workspace }}/Sponge/pom.xml
    - name: Upload Sponge Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tablist-sponge-dev
        path: ${{ github.workspace }}/Sponge/target/tablist-sponge*.jar
